baseURL = "http://beta.nieneb.nl/"
languageCode = "en-us"
title = "Niene Boeijen"
# theme = "hugo-creative-portfolio-theme"

[params]
  style = "yellow"
  sidebarAbout = [ "Hello this is me!</br> </br> I am a full stack web map developer at <a href='https://webmapper.net' target='_blank' > Webmapper </a>. Everything I make is with a creative focus, from geo-data analysis to cartographic visualizations on the web. Check my <a href='/online'>online portfolio</a> for my work online and workshops and presentations. </br></br> In my free time I am always creating things. As artist and tinkerer. Check my <a href='/offline'>offline portfolio</a> for everything physical I create. </br> </br> Want to know more or get into contact with me, check <a href='/about'>about me</a>.</br> </br>I also organize Maptime Amsterdam and Maptime Utrecht."
  ]
  sidebarAbout2 = [ "niene @ webmapper . net "]
 
  email = "niene@webmapper.net"

  [[params.navlinks]]
  name = "Online Portfolio"
  url = "online/"
  home = true

  [[params.navlinks]]
  name = "Offline Portfolio"
  url = "offline/"

  [[params.navlinks]]
  name = "About me"
  url = "about/"

  [[params.navlinks]]
  name = "Maptime"
  url = "maptime/"

  [params.social]
  github = "https://github.com/NieneB"
  twitter = "https://twitter.com/BNiene"
  linkedin = "https://www.linkedin.com/in/niene-boeijen-24a8a429/"

